channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - astropy=4.2.1
  - matplotlib
  - requests
  - jupyterlab>=3.0
  - scipy
  - aplpy
  - pip
  - pip:
    - git+https://github.com/astropy/astroquery.git@77986a0657458898cf21ee590cd7dbc81f9f777a
    - jupyter-offlinenotebook
    - git+https://github.com/astropy/pyvo.git@c7a2ebad95629932775fb0966a6a79aec23b6dda
    - nbgitpuller
    - nbzip
    - jupyter-archive
