#!/bin/bash


jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-offlinenotebook
jupyter nbextension install --py nbzip --sys-prefix
jupyter nbextension enable --py nbzip --sys-prefix
jupyter nbextension install --py jupyter_offlinenotebook --sys-prefix
jupyter nbextension enable --py jupyter_offlinenotebook --sys-prefix
jupyter serverextension enable --py nbgitpuller --sys-prefix
jupyter serverextension enable --py nbzip --sys-prefix
jupyter serverextension enable --py jupyter_offlinenotebook --sys-prefix
