#!/bin/bash


jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyter-offlinenotebook --no-build
jupyter lab build
jupyter nbextension install --py nbzip
jupyter nbextension enable --py nbzip
jupyter nbextension install --py jupyter_offlinenotebook --sys-prefix
jupyter nbextension enable --py jupyter_offlinenotebook --sys-prefix
jupyter serverextension enable --py nbgitpuller --sys-prefix
jupyter serverextension enable --py nbzip --sys-prefix
jupyter serverextension enable --py jupyter_offlinenotebook --sys-prefix
